---
title: Kimuth.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Fjeldvig.net
description: Fjeldvig Øl og Spadserklubb
avatar: https://raw.githubusercontent.com/Kimuth/kimuth.github.io/master/images/beer_avatar.png
footer-links:
  dribbble: 
  email: 
  facebook: groups/177403067286/
  flickr: 
  github: 
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: https://kimuth.github.io/
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
plugins:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
